### ISSUE TITLE
Product ID variable in getFills method is wrongly picked from Profile ID 

### ISSUE THREAD

**Issue by vivekspanicker** [pcrady/coinbase_exchange#1]
It looks like profile ID is wrongly assigned to product ID variable so that it breaks when getAllFills method is called from OrdersClient. Also, there is no variable assigned for profile ID. 

  Future<List<Fill>> getAllFills({
      String? orderId,
      String? productId,
      String? profileId,
      int? limit,
      //TODO determine if int or datetime or dateformat or whatever
      int? before,
      int? after,
    }) async {
      var response = await _ordersRestClient.getAllFills(
        orderId: orderId,
        **productId: profileId,**
        limit: limit,
        before: before,
        after: after,
      );

**Comment by pcrady** [comment]
yeah theres gonna be tons of stuff like that in here. I havnt had time to make proper tests to make sure everything works yet but I'll push a fix for this.

**Comment by pcrady** [comment]
this is fixed with version 0.0.4
